/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2023-08-03 02:42:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vistas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/jose/Desktop/Javaweb%20MVC%20POO-20230802T034113Z-001/Javaweb%20MVC%20POO/CRUDJavaWeb%20OK%2024-Jul-23/CRUDJavaWeb%20OK%2024-Jul-23/build/web/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343837818000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1690172794756L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (session.getAttribute("usuario") != null) {

      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <title>CRUD Usuarios| Inicio</title>\n");
      out.write("        <!-- Tell the browser to be responsive to screen width -->\n");
      out.write("        <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"bower_components/bootstrap/dist/css/bootstrap.min.css\">\n");
      out.write("        <!-- Font Awesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"bower_components/font-awesome/css/font-awesome.min.css\">\n");
      out.write("        <!-- Ionicons -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"bower_components/Ionicons/css/ionicons.min.css\">\n");
      out.write("        <!-- Theme style -->\n");
      out.write("        <link href=\"dist/css/AdminLTE.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("\n");
      out.write("        <!-- AdminLTE Skins. We have chosen the skin-blue for this starter\n");
      out.write("              page. However, you can choose any other skin. Make sure you\n");
      out.write("              apply the skin class to the body tag so the changes take effect. -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"dist/css/skins/skin-blue.min.css\">\n");
      out.write("        <link rel=\"stylesheet\"\n");
      out.write("              href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body class=\"hold-transition skin-blue sidebar-mini\">\n");
      out.write("        <div class=\"wrapper\">\n");
      out.write("\n");
      out.write("            <!-- Main Header -->\n");
      out.write("            <header class=\"main-header\">\n");
      out.write("                <a href=\"#\" class=\"logo\">\n");
      out.write("                    <!-- mini logo for sidebar mini 50x50 pixels -->\n");
      out.write("                    <span class=\"logo-mini\"><b>S</b>BL</span>\n");
      out.write("                    <!-- logo for regular state and mobile devices -->\n");
      out.write("                    <span class=\"logo-lg\"><b>CRUD Usuarios</b></span>\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <!-- Header Navbar -->\n");
      out.write("                <nav class=\"navbar navbar-static-top\" role=\"navigation\">\n");
      out.write("                    <!-- Sidebar toggle button-->\n");
      out.write("                    <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"push-menu\" role=\"button\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    </a>\n");
      out.write("                    <!-- Navbar Right Menu -->\n");
      out.write("                    <div class=\"navbar-custom-menu\">\n");
      out.write("                        <ul class=\"nav navbar-nav\">\n");
      out.write("                            <!-- User Account Menu -->\n");
      out.write("                            <li class=\"dropdown user user-menu\">\n");
      out.write("                                <!-- Menu Toggle Button -->\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                                    <!-- The user image in the navbar-->\n");
      out.write("                                    <img src=\"dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\">\n");
      out.write("                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->\n");
      out.write("                                    <span class=\"hidden-xs\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.nombreUsuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"dropdown-menu\">\n");
      out.write("                                    <!-- The user image in the menu -->\n");
      out.write("                                    <li class=\"user-header\">\n");
      out.write("                                        <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("\n");
      out.write("                                        <p>                    \n");
      out.write("                                            Bienvenido - ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.nombreUsuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("                                            <small>Usted es,");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.cargo.nombreCargo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </small>\n");
      out.write("                                        </p>\n");
      out.write("                                    </li>\n");
      out.write("                                    <!-- Menu Footer-->\n");
      out.write("                                    <li class=\"user-footer\">\n");
      out.write("                                        <div class=\"pull-right\">\n");
      out.write("                                            <a href=\"srvUsuario?accion=cerrar\" class=\"btn btn-default btn-flat\">Cerrar Sesión</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("            </header>\n");
      out.write("            <!-- Left side column. contains the logo and sidebar -->\n");
      out.write("            <aside class=\"main-sidebar\">\n");
      out.write("\n");
      out.write("                <!-- sidebar: style can be found in sidebar.less -->\n");
      out.write("                <section class=\"sidebar\">\n");
      out.write("\n");
      out.write("                    <!-- Sidebar user panel (optional) -->\n");
      out.write("                    <div class=\"user-panel\">\n");
      out.write("                        <div class=\"pull-left image\">\n");
      out.write("                            <img src=\"dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pull-left info\">\n");
      out.write("                            <p>Bienvenido,  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.nombreUsuario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </p>\n");
      out.write("                            <!-- Status -->\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-circle text-success\"></i> Online</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- search form (Optional) -->\n");
      out.write("                    <form action=\"#\" method=\"get\" class=\"sidebar-form\">\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search...\">\n");
      out.write("                            <span class=\"input-group-btn\">\n");
      out.write("                                <button type=\"submit\" name=\"search\" id=\"search-btn\" class=\"btn btn-flat\"><i class=\"fa fa-search\"></i>\n");
      out.write("                                </button>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- /.search form -->\n");
      out.write("\n");
      out.write("                    <!-- Sidebar Menu -->\n");
      out.write("                    <ul class=\"sidebar-menu\" data-widget=\"tree\">\n");
      out.write("                        <li class=\"header\">INICIO</li>\n");
      out.write("                        <!-- Optionally, you can add icons to the links -->\n");
      out.write("                        <li class=\"active\"><a href=\"#\"><i class=\"fa fa-link\"></i> <span>Panel Administrativo</span></a></li>\n");
      out.write("                        <li class=\"treeview\">\n");
      out.write("                            <a href=\"#\"><i class=\"glyphicon glyphicon-th-large\"></i> <span>Registros</span>\n");
      out.write("                                <span class=\"pull-right-container\">\n");
      out.write("                                    <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                            <ul class=\"treeview-menu\">\n");
      out.write("                            <!--    <li><a href=\"#\"><i class=\"fa fa-archive\"></i>Categorias</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-tags\"></i>Marcas</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cube\"></i>Productos</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-users\"></i>Clientes</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-truck\"></i>Proveedores</a></li>\n");
      out.write("                                <li><a href=\"\"><i class=\"fa fa-user-plus\"></i>Empleados</a></li> -->\n");
      out.write("                                <li><a href=\"srvUsuario?accion=listarUsuarios\"><i class=\"fa fa-address-card\"></i>Usuarios</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                 <!--       <li class=\"treeview\">\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-cart-arrow-down\"></i> <span>Ventas</span>\n");
      out.write("                                <span class=\"pull-right-container\">\n");
      out.write("                                    <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                            <ul class=\"treeview-menu\">\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-cart-arrow-down\"></i>Nueva Venta</a></li>\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-tags\"></i>Administrar Ventas</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"treeview\">\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-area-chart\"></i> <span>Reportes</span>\n");
      out.write("                                <span class=\"pull-right-container\">\n");
      out.write("                                    <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                                </span>\n");
      out.write("                            </a>\n");
      out.write("                            <ul class=\"treeview-menu\">\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-bar-chart\"></i>Reportes Ventas</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li> -->\n");
      out.write("                    </ul>\n");
      out.write("                    <!-- /.sidebar-menu -->\n");
      out.write("                </section>\n");
      out.write("                <!-- /.sidebar -->\n");
      out.write("            </aside>\n");
      out.write("\n");
      out.write("            <!-- Content Wrapper. Contains page content -->\n");
      out.write("            <div class=\"content-wrapper\">\n");
      out.write("                <!-- Content Header (Page header) -->\n");
      out.write("                <section class=\"content-header\">\n");
      out.write("                    <h1>\n");
      out.write("                        Página Principal\n");
      out.write("                    </h1>\n");
      out.write("                    <ol class=\"breadcrumb\">\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> Inicio</a></li>\n");
      out.write("                        <li class=\"active\">Panel Administrativo</li>\n");
      out.write("                    </ol>\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("                <section class=\"content\">\n");
      out.write("                    <!-- Small boxes (Stat box) -->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"container\">\n");
      out.write("                        <div class=\"col-lg-8 col-xs-6\">\n");
      out.write("                            <!-- small box -->\n");
      out.write("                            <div class=\"small-box bg-aqua\">\n");
      out.write("                                <div class=\"inner\">\n");
      out.write("                                    <h3>Bienvenidos al CRUD de Usuarios</h3>\n");
      out.write("\n");
      out.write("                                    <a href=\"srvUsuario?accion=nuevo\">\n");
      out.write("                        <i class=\"fa fa-plus\"></i> Nuevo Usuario </a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"icon\">\n");
      out.write("                                    <i class=\"ion ion-bag\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <a href=\"srvUsuario?accion=listarUsuarios\" class=\"small-box-footer\">Más info <i class=\"fa fa-arrow-circle-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- ./col -->\n");
      out.write("                   <!--       <div class=\"col-lg-3 col-xs-6\">\n");
      out.write("                            <!-- small box -->\n");
      out.write("                     <!--       <div class=\"small-box bg-green\">\n");
      out.write("                                <div class=\"inner\">\n");
      out.write("                                    <h3>53<sup style=\"font-size: 20px\">%</sup></h3>\n");
      out.write("\n");
      out.write("                                    <p>Bounce Rate</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"icon\">\n");
      out.write("                                    <i class=\"ion ion-stats-bars\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <a href=\"#\" class=\"small-box-footer\">More info <i class=\"fa fa-arrow-circle-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div> -->\n");
      out.write("                        <!-- ./col -->\n");
      out.write("                  <!--        <div class=\"col-lg-3 col-xs-6\">\n");
      out.write("                            <!-- small box -->\n");
      out.write("                 <!--           <div class=\"small-box bg-yellow\">\n");
      out.write("                                <div class=\"inner\">\n");
      out.write("                                    <h3>44</h3>\n");
      out.write("\n");
      out.write("                                    <p>User Registrations</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"icon\">\n");
      out.write("                                    <i class=\"ion ion-person-add\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <a href=\"#\" class=\"small-box-footer\">More info <i class=\"fa fa-arrow-circle-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div> -->\n");
      out.write("                        <!-- ./col -->\n");
      out.write("                  <!--        <div class=\"col-lg-3 col-xs-6\">\n");
      out.write("                            <!-- small box -->\n");
      out.write("                 <!--           <div class=\"small-box bg-red\">\n");
      out.write("                                <div class=\"inner\">\n");
      out.write("                                    <h3>65</h3>\n");
      out.write("\n");
      out.write("                                    <p>Unique Visitors</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"icon\">\n");
      out.write("                                    <i class=\"ion ion-pie-graph\"></i>\n");
      out.write("                                </div>\n");
      out.write("                                <a href=\"#\" class=\"small-box-footer\">More info <i class=\"fa fa-arrow-circle-right\"></i></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div> -->\n");
      out.write("                        <!-- ./col -->\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("                <!-- /.content -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.content-wrapper -->\n");
      out.write("\n");
      out.write("            <!-- Main Footer -->\n");
      out.write("            <footer class=\"main-footer\">\n");
      out.write("                <!-- To the right -->\n");
      out.write("                <div class=\"pull-right hidden-xs\">\n");
      out.write("                    “Lo que haces hoy puede mejorar todos tus mañanas.” Ralph Marston\n");
      out.write("                </div>\n");
      out.write("                <!-- Default to the left -->\n");
      out.write("                <strong>Copyright &copy; 2023 <a href=\"#\">Inmasoft</a>.</strong> Todos los derechos reservados.\n");
      out.write("            </footer>\n");
      out.write("\n");
      out.write("            <div class=\"control-sidebar-bg\"></div>\n");
      out.write("        </div>\n");
      out.write("        <!-- ./wrapper -->\n");
      out.write("\n");
      out.write("        <!-- REQUIRED JS SCRIPTS -->\n");
      out.write("\n");
      out.write("        <!-- jQuery 3 -->\n");
      out.write("        <script src=\"bower_components/jquery/dist/jquery.min.js\"></script>\n");
      out.write("        <!-- Bootstrap 3.3.7 -->\n");
      out.write("        <script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n");
      out.write("        <!-- AdminLTE App -->\n");
      out.write("        <script src=\"dist/js/adminlte.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!-- Optionally, you can add Slimscroll and FastClick plugins.\n");
      out.write("             Both of these plugins are recommended to enhance the\n");
      out.write("             user experience. -->\n");
      out.write("    </body>\n");
      out.write("</html>\n");

    } else {
        response.sendRedirect("identificar.jsp");
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
